---
- hosts: dbservers
  vars_files: 
    - var.yml

  tasks:
  - name: updating repository cache
    apt: update_cache=yes   

  - name: Installing postgres
    apt: name=postgresql-server state=latest

    notify:
      - restart postgresql-server

  - name: Enabling and configuring postgres DB
    shell: |
      sudo  service postgresql initdb
      sudo postgresql-setup --initdb
      sudo systemctl enable postgresql.service
      sudo systemctl start postgresql.service
      sudo -u postgres psql -U postgres -d postgres -c "alter user postgres with password 'password';"
      sudo echo "listen_addresses = '*'" >> /var/lib/pgsql/data/postgresql.conf
      sudo sed -i '/^host/d' /var/lib/pgsql/data/pg_hba.conf
      sudo echo "host all all 0.0.0.0/0 md5" >> /var/lib/pgsql/data/pg_hba.conf
      sudo systemctl restart postgresql.service

  handlers:
    - name: restart postgresql-server
      service: name=postgresql-serverr state=reloaded